FROM alpine:3.12

RUN apk add --no-cache --upgrade bash
COPY script.sh script.sh
RUN chmod +x script.sh

ENV EXECUTION_MINUTES=1

COPY cloudrun/cloudrun_listener.sh cloudrun_listener.sh
COPY cloudrun/cloudrun_script.sh cloudrun_script.sh
RUN chmod +x cloudrun_listener.sh cloudrun_script.sh

ENTRYPOINT [ "./cloudrun_listener.sh" ]